
version: '3'

services:
  review-collector:
    image: teixeirafernando/review-collector:latest
    environment:
      - AWS_ACCESSKEY=${AWS_ACCESSKEY}
      - AWS_SECRETKEY=${AWS_SECRETKEY}
    container_name: review-collector
    ports:
      - "8080:8080"

  review-analyzer:
    image: teixeirafernando/review-analyzer:latest
    environment:
      - AWS_ACCESSKEY=${AWS_ACCESSKEY}
      - AWS_SECRETKEY=${AWS_SECRETKEY}
    container_name: review-analyzer
    ports:
      - "8081:8081"

  frontend-review:
    image: teixeirafernando/frontend-review:latest
    container_name: frontend-review
    ports:
      - "3000:80"

  e2e-tests:
    image: teixeirafernando/review-analysis-e2e-tests:latest
    environment:
      - REVIEW_COLLECTOR_BASE_URL=review-collector
      - REVIEW_ANALYZER_BASE_URL=review-analyzer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - review-collector
      - review-analyzer
    entrypoint: ["sh", "-c", "while ! nc -z review-collector 8080; do sleep 1; done; while ! nc -z review-analyzer 8081; do sleep 1; done; ./gradlew :e2e-tests:test --tests '*ReviewAnalysisE2ETest'"]

