name: Frontend Review - Pull Request
on:
  pull_request:
    branches: ["main"]
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd frontend-review
          npm ci
      - name: Lint
        run: |
          cd frontend-review
          npm run lint || true
      - name: Build
        run: |
          cd frontend-review
          npm run build
      - name: Test
        run: |
          cd frontend-review
          npm test || true
      - name: Build Docker image
        run: |
          cd frontend-review
          docker build -t teixeirafernando/frontend-review:pr-${{ github.run_number }} .
