name: Review Collector - Continuous Integration

on:
  pull_request:
    paths:
      - 'review-collector/**'
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@cc4fc85e6b35bafd578d5ffbc76a5518407e1af0 # v4.2.1

      - name: Build with Gradle
        run: ./gradlew :review-collector:build

      - name: Test with Gradle
        run: ./gradlew :review-collector:test

